import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  weight: "100",
  weight: "200",
  weight: "300",
  weight: "400",
  weight: "500",
  weight: "600",
  weight: "700",
  weight: "800",
  weight: "900",
  subsets: ["latin"],
  display: "swap",
});
import Script from "next/script";
export const metadata = {
  title: "Learning Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Development = process.env.NODE_ENV;
  const NAME = process.env.DEV_NAME;
  console.log(Development, NAME);
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>

      <body className={poppins.className}>
        {children}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
