"use client";
import Link from "next/link";
import styles from "./page.module.css";
import custom from "@/css/custom.module.css";
import { useState } from "react";

// Static MetaData This will Work only in Server Side Component.
export const metadata = {
  title: "Learning Next Js | Home",
  description: "Generated by create next app",
};

const Home = () => {
  const [color, setColor] = useState(false);
  const { red, green, orange } = custom;

  return (
    <main className={styles.main}>
      <h1 className={color ? red : green}>Home Page</h1>
      <button className="btn btn-primary" onClick={() => setColor(!color)}>
        Change Home Page Text Color
      </button>
      <Link href="/about" id={orange}>
        About
      </Link>
      <br />
      <Link href="/blog">Blog</Link>
      <br />
      <Link href="/login">Login</Link>
    </main>
  );
};

export default Home;
